### numpy基本概念
> - 用于数据整理和清理，子集构造和过滤，转换等快速的矢量化数组运算
> - 常用的数组算法，比如排序，唯一化，集合运算
> - 高效的描述统计和数据聚合个摘要运算
> - 异构数据集的合并/连接运算的数据对齐和关系型数据运算
> - 数据的分组计算

#### 为什么数据处理要用numpy
> -Numpy是在一个连续的内存中存储数据，独立于其他的python内置对象，Numpy的c语言编写的算法库可以操作内存，而不必进行类型检查和其他前期工作
> - Numpy可以在整个数组上面进行复杂的计算，而不需要python的for循环

#### ndarray：多维数组对象
> 一个快速灵活的大数据集容器,我们经常说的「数组」，「Numpy数组」，「ndarry」基本指的都是ndarry对象

### ndarray&DataFrame&list的相互转化

In [5]:
import pandas as pd
import numpy as np
data = np.array([[1,5,8],[3,6,4],[7,5,1]])
df = pd.DataFrame([4,48,5,9])

# ndarray --> DataFrame
data_df = pd.DataFrame(data)
print(data_df)
print(type(data_df))

   0  1  2
0  1  5  8
1  3  6  4
2  7  5  1
<class 'pandas.core.frame.DataFrame'>


In [7]:
# DataFrame/Series -->ndarray
# 方法1 .values  记住没有括号
data_ndarry = df.values
print(data_ndarry)
print(type(data_ndarry))
print("<--------方法分割线------->")
# 方法2：.as_.as_matrix() 此方法正在被逐步淘汰
data_ndarry2 = df.as_matrix()
print(data_ndarry2)
print(type(data_ndarry2))

[[ 4]
 [48]
 [ 5]
 [ 9]]
<class 'numpy.ndarray'>
<--------方法分割线------->
[[ 4]
 [48]
 [ 5]
 [ 9]]
<class 'numpy.ndarray'>


D:\Anaconda\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [11]:
# list -->DataFrame/ndarray
li = [[1,2,3],[4,5,6],[7,7,9]]
li_df = pd.DataFrame(li)
print(li_df)
print(type(li_df))
print("<--------------分割线------------->")
li_nda= np.array(li)
print(li_nda)
print(type(li_nda))

   0  1  2
0  1  2  3
1  4  5  6
2  7  7  9
<class 'pandas.core.frame.DataFrame'>
<--------------分割线------------->
[[1 2 3]
 [4 5 6]
 [7 7 9]]
<class 'numpy.ndarray'>


In [19]:
# DataFrame/ndarray --> list

# 这里需要注意下：一般没有直接将DF转换成list，
# 多半是先转化成ndarray在转化成list,(每一行作为一个列表)
df_nda = np.array(data_df)
df_li =df_nda.tolist()
# 或者 data_df.values.tolist(),可以说是目前最简单的方法
print(df_li)
print(type(df_li))
# 将每行的值作为一个子列表

[[1, 5, 8], [3, 6, 4], [7, 5, 1]]
<class 'list'>
